#!/bin/zsh

echo hello world

for dir in assets/*; do
    echo "$dir"
    touch "$dir"/hello
    rm $dir/hello
    echo "" > $dir/readme.md
    for file in $dir/*
        echo "<img src=\"""${file##*/}"\"\> >> $dir/readme.md
done
